import fs from "node:fs";
import path from "node:path";
import { listMemories, paths } from "./storage.js";

const SECTIONS = [
  ["Architecture Decisions", ["decision"]],
  ["Conventions", ["convention"]],
  ["Preferred Patterns", ["fix", "lesson"]],
  ["Known Pitfalls", ["bug", "failed_attempt", "warning"]],
  ["Open Follow-Ups", ["todo"]]
];

export function generateAgentsMarkdown({ root = process.cwd(), limitPerSection = 12 } = {}) {
  const memories = listMemories(root)
    .filter((memory) => Number(memory.confidence || 0) >= 0.45)
    .sort((a, b) => Number(b.usefulness || b.confidence || 0) - Number(a.usefulness || a.confidence || 0));

  const lines = [
    "# CodexMemory Project Instructions",
    "",
    "Generated by CodexMemory from approved local memories.",
    "",
    "Use these rules as durable repository context. Prefer current source code when it conflicts with memory, and surface the conflict before acting.",
    ""
  ];

  if (memories.length === 0) {
    lines.push(
      "## No Approved Memories Yet",
      "",
      "No approved memories exist yet. After completing a task, run reflection and review pending learnings before regenerating this file with `codexmemory learn`.",
      ""
    );
  }

  for (const [title, types] of SECTIONS) {
    const items = memories.filter((memory) => types.includes(memory.type)).slice(0, limitPerSection);
    if (items.length === 0) continue;
    lines.push(`## ${title}`, "");
    for (const memory of items) {
      const guidance = ruleFromMemory(memory);
      const files = memory.code_paths?.length ? ` (${memory.code_paths.join(", ")})` : "";
      lines.push(`- ${guidance}${files}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

export function ruleFromMemory(memory) {
  const next = clean(memory.next_time);
  const body = clean(memory.body);
  const rationale = clean(memory.rationale).replace(/^Reason captured from task notes:\s*/i, "");

  if (next && !isGenericGuidance(next)) return ensurePeriod(next);
  if (body && rationale && !body.toLowerCase().includes(rationale.toLowerCase())) {
    return ensurePeriod(`${body} because ${rationale}`);
  }
  if (body) return ensurePeriod(body);
  return ensurePeriod(memory.title);
}

function clean(value) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function isGenericGuidance(value) {
  return [
    /^apply this context when a future task touches the same area\.?$/i,
    /^use this memory when the task touches related code or decisions\.?$/i,
    /^avoid repeating this attempt unless the underlying constraint has changed\.?$/i,
    /^reuse this fix pattern when the same symptom appears\.?$/i
  ].some((pattern) => pattern.test(value));
}

function ensurePeriod(value) {
  return /[.!?]$/.test(value) ? value : `${value}.`;
}

export function writeAgentsFile({ root = process.cwd() } = {}) {
  const p = paths(root);
  fs.mkdirSync(p.base, { recursive: true });
  const filePath = path.join(p.base, "AGENTS.md");
  fs.writeFileSync(filePath, generateAgentsMarkdown({ root }));
  return filePath;
}
